### ISSUE TITLE
벌레 조회 기능 구현

### ISSUE THREAD

**Issue by kmebin** [team-moabam/moabam-BE#11]
### 📋 Checklist

- [X] 📁 프로젝트는 등록했나요?
- [X] 🎯 마일스톤은 등록했나요?

### ✅ Tasks

- [x] 관련 엔티티 생성
- [x] 벌레 조회 API 구현 
- [x] 벌레 조회 기능 테스트
