### ISSUE TITLE
쿠폰 발행 기능 구현

### ISSUE THREAD

**Issue by HyuckJuneHong** [team-moabam/moabam-BE#30]
### 📋 Checklist

- [X] 📁 프로젝트는 등록했나요?
- [X] 🎯 마일스톤은 등록했나요?

### ✅ Tasks

- [x] 쿠폰 엔티티 설계
- [x] 쿠폰 발행 API 구현
- [x] 쿠폰 발행 API 테스트

### 🙋🏻 More

- 해당 API는 관리자 쪽에서 사용하는 기능입니다.
- 일반 회원은 사용할 수 없습니다.
