### ISSUE TITLE
쿠폰 조회 기능 구현

### ISSUE THREAD

**Issue by HyuckJuneHong** [team-moabam/moabam-BE#32]
### 📋 Checklist

- [X] 📁 프로젝트는 등록했나요?
- [X] 🎯 마일스톤은 등록했나요?

### ✅ Tasks

- [x] 특정 쿠폰 조회 API 기능 구현
- [x] 특정 쿠폰 조회 API 기능 테스트
- [x] 상태에 따른 쿠폰 조회 API 기능 구현
- [x] 상태에 따른 쿠폰 조회 API 기능 테스트
