### ISSUE TITLE
아이템/벌레 컨트롤러 테스트 리팩토링 및 @CurrentMember 적용

### ISSUE THREAD

**Issue by kmebin** [team-moabam/moabam-BE#56]
### 📋 Checklist

- [X] 🏷 필요한 라벨만 등록했나요?
- [X] 📁 프로젝트는 등록했나요?
- [X] 🎯 마일스톤은 등록했나요?

### ✅ Tasks

- [x] 아이템 Controller 통합 테스트
- [x] 벌레 Controller 통합 테스트
- [x] 모든 담당 API에 CurrentMember 적용
